# Generated by Django 4.0.5 on 2022-07-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('photo', models.ImageField(upload_to='products', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ingridients', models.TextField(verbose_name='Состав')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
