# Generated by Django 4.0.5 on 2022-07-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='')),
                ('country', models.CharField(max_length=255, verbose_name='Страна производства')),
                ('photo', models.ImageField(upload_to='category', verbose_name='Фото')),
                ('product', models.ManyToManyField(related_name='category', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
