# Generated by Django 4.0.5 on 2022-06-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentify', '0002_rename_birthdate_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='Дата Рождения'),
        ),
    ]
